### ISSUE TITLE
Render pages using SiteMesh 3

### ISSUE THREAD

**Issue by cgendreau** [Canadensys/vascan#23]
Vascan should start to use the [canadensys-web-core](https://github.com/Canadensys/canadensys-web-core) and [canadensys-web-theme](https://github.com/Canadensys/canadensys-web-theme) projects. Those components should be resused in Canadensys web apps. SiteMesh3 is required in order to reuse the Canadensys theme but is also very useful to simplify page layout.

**Comment by cgendreau** [comment]
2 possible solutions:

### Spring Freemarker ViewResolver
Reuse the Freemarker ViewResolver to resolve the decorator templates by simply adding a `@RequestMapping` annotation for `/decorators/*` in the controller. Then, return a ModelAndView object for the decorator. This solution is fast to implement but bring new issues. This solution exposes the URL for the layout so an internal check must be done to only accept internal forward. It also becomes error prone in case a decorator and a view would have the same name since they both load from the same ViewResolver.

### ServletWrappingController
Use the [ServletWrappingController](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/ServletWrappingController.html) to wrap our implementation of `FreemarkerServlet`. Then, use [SimpleUrlHandlerMapping](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/handler/SimpleUrlHandlerMapping.html) to map decorator URLs to our controller. Note that `ServletWrappingController` will not give the expected result when calling `getPathInfo` (always null), this needs to be solved in our FreemarkerServlet implementation.

**Comment by dshorthouse** [comment]
Which of the two solutions are easiest to maintain and least prone to confusion later? At first glance, it seems like the second solution is best to avoid potential clashes with decorator and view naming.

**Comment by cgendreau** [comment]
yes the second solution will be used.

**Comment by cgendreau** [comment]
For the records, `ServletWrappingController` will not used because dependency injection is required by our setup. Instead, we will instantiate our `SpringFreemarkerDecoratorServlet` and use it with Spring's `SimpleServletHandlerAdapter`.
