### ISSUE TITLE
Claytosmunda

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan#40]
Bonjour Carole

Luc voit ce taxon quand il effectue une recherche, mais j'obtiens aucun résultat de mon côté.  J'ai essayé avec Google Chrome et Internet Explorer sans succès.  Ordinateur PC windows 7 et iPhone SE

**Comment by CaroleSinou** [comment]
La page d'espèce est présente et visible : [Claytosmunda claytoniana](https://data.canadensys.net/vascan/taxon/31529), tout comme celle pour le genre : [Claytosmunda ](https://data.canadensys.net/vascan/taxon/31528)

Néanmoins, une recherche par nom d'espèce ou de genre ne donne aucun résultat:
 - https://data.canadensys.net/vascan/search?q=Claytosmunda
 - https://data.canadensys.net/vascan/search?q=Claytosmunda+claytoniana

**Comment by CaroleSinou** [comment]
Le problème semble avoir été résolu, donc je ferme l'issue.
@FredCoursol laisse moi savoir si tu c'est encore un problème de ton côté.
